package com.swing.foodserving.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user")
@Inheritance(strategy=InheritanceType.JOINED)  

public class User extends AbstractTimestampEntityWithActiveAndDelete implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 898029952524941595L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	private Integer userId;
	
	@Column(name = "username", unique = true, length = 50)
	private String username;
	
	@Column(name = "name", length = 100)
	private String name;
	
	@Column(name = "gender")
	private int gender;
	
	@Column(name = "email", length = 100)
	private String email;
	
	@Column(name = "mobile", length = 15)
	private String mobile;
	
	@Column(name = "role", length = 10)
	private int role;
	
	@Column(name = "profile_pic")
	private String profilePic;
	
	@Column(name="is_mobile_verifiyed" ,columnDefinition="SMALLINT(1) default 0 COMMENT ' 1 = verifiyed, 0 = un-verifiyed'")
	int isMobileVerifiyed;
	
	@Column(name="is_email_verifiyed", columnDefinition="SMALLINT(1) default 0 COMMENT ' 1 = verifiyed, 0 = un-verifiyed'")
	int isEmailVerifiyed;
	
	@Column(name = "vendor_avilable")
	private String vendorAvilable;
	
	@JsonIgnore
	@Column(name = "password")
	private String password;
	
	@Column(name="password_reset_token",nullable=true)
	private String passwordResetToken;
	
	@Column(name = "password_reset_token_time")
	private Date passwordResetTokenTime;

	

	public User() {
	}

	public User(String username, String password,String email,int role) {
		this.username = username;
		this.password = password;
		this.role = role;
		this.email = email;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getProfilePic() {
		return profilePic;
	}

	public void setProfilePic(String profilePic) {
		this.profilePic = profilePic;
	}

	public int getIsMobileVerifiyed() {
		return isMobileVerifiyed;
	}

	public void setIsMobileVerifiyed(int isMobileVerifiyed) {
		this.isMobileVerifiyed = isMobileVerifiyed;
	}

	public int getIsEmailVerifiyed() {
		return isEmailVerifiyed;
	}

	public void setIsEmailVerifiyed(int isEmailVerifiyed) {
		this.isEmailVerifiyed = isEmailVerifiyed;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getGender() {
		return gender;
	}

	public void setGender(int gender) {
		this.gender = gender;
	}

	public int getRole() {
		return role;
	}

	public void setRole(int role) {
		this.role = role;
	}

	public String getVendorAvilable() {
		return vendorAvilable;
	}

	public void setVendorAvilable(String vendorAvilable) {
		this.vendorAvilable = vendorAvilable;
	}

	public Date getPasswordResetTokenTime() {
		return passwordResetTokenTime;
	}

	public void setPasswordResetTokenTime(Date passwordResetTokenTime) {
		this.passwordResetTokenTime = passwordResetTokenTime;
	}

	public String getPasswordResetToken() {
		return passwordResetToken;
	}

	public void setPasswordResetToken(String passwordResetToken) {
		this.passwordResetToken = passwordResetToken;
	}

}
